version: 2
updates:
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.25.0
  - dependency-name: nuxt
    versions:
    - 2.15.1
  - dependency-name: highcharts
    versions:
    - 9.0.0
  - dependency-name: "@turf/point-on-feature"
    versions:
    - 6.3.0
  - dependency-name: "@nuxtjs/axios"
    versions:
    - 5.12.5
