language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
git:
  depth: 1


before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11-postgis-2.5 postgresql-11-postgis-2.5-scripts
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

install:
  - pip install -r api/requirements.txt -r api/dev-requirements.txt
  - cd frontend && npm install && cd ..

before_script:
  - psql -U postgres -c "CREATE USER travis"
  - psql -c "create database travis_test with owner travis" -U postgres
  - psql -d travis_test -c "create extension postgis"
  - psql -d travis_test -c "create extension pgcrypto"

env:
  DB_URL: postgresql:///travis_test

script:
  - pytest api/test
  - cd frontend && npm run test && cd ..
