language: python
dist: bionic
python:
  - "3.6"
  - "3.7"

services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11-postgis-2.5

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

install:
  - pip install -r api/requirements.txt -r api/dev-requirements.txt
  - cd frontend && npm install

before_script:
  - psql -c "create database travis_test" -U postgres
  - psql -U postgres -d travis_test -c "create extension postgis"

env:
  DB_URL: postgresql:///travis_test

script:
  - pytest api/test
  - cd frontend && npm run test
