version: '3.7'
services:
  api:
    build:
      context: api
    environment:
      DB_URL: postgresql://nivo:${POSTGRES_PASSWORD:-nivo}@db/nivo
      ENV: PROD
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nivo.desgran.ge,Path:/api"
  db:
    image: mdillon/postgis:11
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nivo}
      POSTGRES_USER: nivo
      POSTGRES_DB: nivo
  front:
    build:
      context: frontend
    environment:
      NODE_ENV: production
    depends_on:
      - api
    ports:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nivo.desgran.ge"
  proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
