version: '3.7'
services:
  api:
    build:
      context: api
    environment:
      DB_URL: postgresql://nivo:${POSTGRES_PASSWORD:-nivo}@db/nivo
      ENV: PROD
      SENTRY_DSN: ${SENTRY_DSN:-}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.nivo.desgran.ge"
  db:
    image: mdillon/postgis:11
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nivo}
      POSTGRES_USER: nivo
      POSTGRES_DB: nivo
  front:
    build:
      context: frontend
    environment:
      NODE_ENV: production
      VUE_APP_BASE_URL: api.nivo.desgran.ge
      SENTRY_DSN: ${SENTRY_DSN:-}
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nivo.desgran.ge"
  proxy:
    image: traefik
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
