# the frontend is deployed on netlify. But that's just a detail
[build]
base = "frontend/"
publish = "dist/"
command = "npm run build"

[[headers]]
for = "/*"
  [headers.values]
  Referrer-Policy = "origin"
  X-Content-Type-Options =  "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"

[[redirects]]
for = "/:id"
to = "/"
status = 200

for = '/flowcapt/:id'
to = '/flowcapt'
status = 200

for = '/poste-nivo/:id'
to = '/poste-nivo'
status = 200