# the frontend is deployed on netlify. But that's just a detail
[build]
base = "frontend/"
publish = "dist/"
command = "npm run build"

[[headers]]
for = "/*"
  [headers.values]
  Referrer-Policy = "origin"
  X-Content-Type-Options =  "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"

[[redirects]]
for = "/*"
to = "/"