#!/bin/bash

init_db
if [[ $ENV == "DEV" ]]; then
    echo "Dev env importing last nivo data and bra"
    import_massifs
    import_nivo_sensor_station
    import_flowcapt_station
    import_last_nivo_data
    import_bra 2019-01-01
fi
