export const mutationTypes = {
  SET_ALERT: 'SET_ALERT',
  DECREASE_ALERT_DURATION: 'DECREASE_ALERT_DURATION',
  REMOVE_ALERT: 'REMOVE_ALERT',
  TOGGLE_MASSIFS_LOADING: 'TOGGLE_TOGGLE_MASSIFS_LOADING',
  TOGGLE_NIVOSE_DATA_LOADING: 'TOGGLE_NIVOSE_DATA_LOADING',
  TOGGLE_FLOWCAPT_LOADING: 'TOGGLE_FLOWCAPT_LOADING',
  TOGGLE_NIVOSE_STATION_LOADING: 'TOGGLE_NIVOSE_STATION_LOADING',
  TOGGLE_BRA_LOADING: 'BRA_LOADING',
  // Loading mutations
  BRA_LOADED: 'BRA_LOADED',
  MASSIFS_LOADED: 'MASSIFS_LOADED',
  NIVOSE_DATA_LOADED: 'NIVOSE_DATA_LOADED',
  NIVOSE_STATION_LOADED: 'NIVOSE_STATION_LOADED',
  FLOWCAPT_LOADED: 'FLOWCAPT_LOADED'
}

export const alertTypes = {
  PRIMARY: 'primary',
  SECONDARY: 'secondary',
  SUCCESS: 'success',
  DANGER: 'danger',
  WARNING: 'warning',
  INFO: 'info',
  LIGHT: 'light',
  DARK: 'dark'
}
