export const mutationTypes = {
  SET_ALERT: 'SET_ALERT',
  SET_SELECTED_BRA: 'SET_SELECTED_BRA',
  DECREASE_ALERT_DURATION: 'DECREASE_ALERT_DURATION',
  REMOVE_ALERT: 'REMOVE_ALERT',
  TOGGLE_MASSIFS_LOADING: 'TOGGLE_TOGGLE_MASSIFS_LOADING',
  TOGGLE_NIVO_DATA_LOADING: 'TOGGLE_NIVO_DATA_LOADING',
  TOGGLE_FLOWCAPT_LOADING: 'TOGGLE_FLOWCAPT_LOADING',
  TOGGLE_NIVO_STATION_LOADING: 'TOGGLE_NIVO_STATION_LOADING',
  TOGGLE_BRA_LOADING: 'BRA_LOADING',
  // Loading mutations
  BRA_LOADED: 'BRA_LOADED',
  MASSIFS_LOADED: 'MASSIFS_LOADED',
  NIVO_DATA_LOADED: 'NIVO_DATA_LOADED',
  NIVO_STATION_LOADED: 'NIVO_STATION_LOADED',
  FLOWCAPT_STATION_LOADED: 'FLOWCAPT_STATION_LOADED',
  FLOWCAPT_DATA_LOADED: 'FLOWCAPT_DATA_LOADED'
}

export const alertTypes = {
  PRIMARY: 'primary',
  SECONDARY: 'secondary',
  SUCCESS: 'success',
  DANGER: 'danger',
  WARNING: 'warning',
  INFO: 'info',
  LIGHT: 'light',
  DARK: 'dark'
}
