version: '3.7'
services:
  app:
    build: .
    ports:
      - 9000:9000
    environment:
      DB_URL: postgresql://nivo:nivo@db/nivo
      ENV: PROD
      LOG_LEVEL: WARNING
    depends_on:
      - db
  db:
    image: camptocamp/postgres:13-postgis-3
    environment:
      POSTGRES_PASSWORD: nivo
      POSTGRES_USER: nivo
      POSTGRES_DB: nivo
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:

