name: Frontend test and build

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      working-directory: frontend/
      run: |
        npm install
        
    # - name: test
    #   run: |
    #     cd frontend
    #     npm test
    
    - name: build
      working-directory: frontend/
      run: |
        npm run build
